In [4]:
import pandas as pd
path = "data/Canada_Demog.csv"

df = pd.read_csv(path, encoding="ISO-8859-1")
df.head()

,CENSUS_YEAR,DGUID,ALT_GEO_CODE,GEO_LEVEL,GEO_NAME,TNR_SF,TNR_LF,DATA_QUALITY_FLAG,CHARACTERISTIC_ID,CHARACTERISTIC_NAME,...,C2_COUNT_MEN+,SYMBOL.1,C3_COUNT_WOMEN+,SYMBOL.2,C10_RATE_TOTAL,SYMBOL.3,C11_RATE_MEN+,SYMBOL.4,C12_RATE_WOMEN+,SYMBOL.5
0,2021,2021A000011124,1,Country,Canada,3.1,4.3,20000,1,"Population, 2021",...,NaN,...,NaN,...,NaN,...,NaN,...,NaN,...
1,2021,2021A000011124,1,Country,Canada,3.1,4.3,20000,2,"Population, 2016",...,NaN,...,NaN,...,NaN,...,NaN,...,NaN,...
2,2021,2021A000011124,1,Country,Canada,3.1,4.3,20000,3,"Population percentage change, 2016 to 2021",...,NaN,...,NaN,...,5.2,NaN,NaN,...,NaN,...
3,2021,2021A000011124,1,Country,Canada,3.1,4.3,20000,4,Total private dwellings,...,NaN,...,NaN,...,NaN,...,NaN,...,NaN,...
4,2021,2021A000011124,1,Country,Canada,3.1,4.3,20000,5,Private dwellings occupied by usual residents,...,NaN,...,NaN,...,NaN,...,NaN,...,NaN,...